<script>
    var $Binder=$Binder||{};$Binder.plugins=$Binder.plugins||[];
    (function(k,f){function t(b,c){h[b]=h[b]||[];h[b].push({cb:c,context:this})}function u(b,c){h[b]&&h[b].forEach(function(b,a){b.cb.apply(b.context,[c])})}function v(b,c,d){k.plugins.forEach(function(a,g){a(b,c,d,e)})}function w(b){var c=this;f.ajax({url:b.url,type:b.type,data:b.data,success:function(d){b.success.apply(c,[d])},error:function(d){b.error.apply(c,[d])}})}function x(b){b.listen=t;b.publish=u;return b}function y(b){b.ajax=w;return b}function m(b,c,d){for(var a in d)0<=a.indexOf(b)&&d[a].forEach(function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           b){a(c)})}function p(b,c,d){"object"==typeof c&&"number"==typeof c.length?(console.log("is - array",b,c),c=function(a){a.push=function(a){"object"==typeof a&&"undefined"==typeof a.length&&(a=n(a,d));console.log("notified");var c=Array.prototype.push.apply(this,[a]);m(b,a,d);return c};a.splice=function(a,c){console.log("notified");var g=Array.prototype.splice.apply(this,[a,c]);m(b,null,d);return g};return a}(c)):console.log("Not array",b,c)}function n(b,c){for(var d in b)b.hasOwnProperty(d)&&"function"!=
    typeof b[d]&&function(a,b){var d=null;p(a,b[a],c);d=b[a];Object.defineProperty(b,a,{set:function(b){p(a,b,c);d=b;m(a,d,c)},get:function(){return d}})}(d,b);b=x(b);return b=y(b)}function e(b,c,d,a){b.find("["+c+"]").each(function(){var b=f(this),l=c.split("-").join("_");if(!b.attr("_bound_"+l)){b.attr("_bound_"+l,"_bound");var e=b.attr(c);l=new Function("a,b,c","with(a){ return "+e+" ;}");a[e]=a[e]||[];d({expressionString:e,expression:l,$el:b,listen:function(b){console.log(a,e);b();a[e].push(b)}})}})}
        function z(b,c,d){A.forEach(function(a,g){e(b,"b-"+a,function(b){b.listen(function(){b.$el.attr(a,b.expression(c));console.log(a,b.expression(c))})},d)})}function B(b,c,d){e(b,"b-sync",function(a){if(a.$el.is('[type="checkbox"]')||a.$el.is('[type="radio"]'))a.$el.on("click",function(){f(this).is(":checked")?c[a.expressionString]=f(this).val():c[a.expressionString]=null});else if(a.$el.is("select"))a.$el.on("change",function(){c[a.expressionString]=f(this).val()});else a.$el.on("keyup",function(){c[a.expressionString]=
            f(this).val()});a.listen(function(b){a.$el.val(c[a.expressionString])})},d)}function C(b,c,d){e(b,"b-on",function(a){var b=a.expression(c);a.$el.on(b[0],function(){c.$el=a.$el;b[1].apply(c,[c])})},d)}function D(b,c,d){e(b,"b-css",function(a){a.listen(function(){a.$el.css(a.expression(c))})},d)}function E(b,c,d){e(b,"b-show",function(a){a.listen(function(b){console.log(a.expression(c),a.expressionString,a.$el);a.expression(c)?a.$el.show():a.$el.hide()})},d)}function F(b,c,d){e(b,"b-hide",function(a){a.listen(function(b){a.expression(c)?
            a.$el.hide():a.$el.show()})},d)}function G(b,c,d){e(b,"b-loop",function(a){var b=a.$el.find("script").html();a.listen(function(){a.$el.html("");a.expression(c).forEach(function(c,d){var g=f(b);a.$el.append(g);g={};var e=n(c,g);console.log(e);q(a.$el,e,g)})})},d)}function H(b,c,d){e(b,"b-slide-up",function(a){a.listen(function(){a.expression(c)?a.$el.slideUp():a.$el.slideDown()})},d)}function I(b,c,d){e(b,"b-slide-down",function(a){a.listen(function(){a.expression(c)?a.$el.slideDown():a.$el.slideUp()})},
            d)}function J(b,c,d){e(b,"b-checked-state",function(a){a.$el.on("click",function(){c[a.expressionString]=f(this).is(":checked")});a.listen(function(){a.$el.prop("checked",a.expression(c))})},d)}function K(b,c,d){e(b,"b-text",function(a){a.listen(function(){a.$el.text(a.expression(c))})},d)}function L(b,c,d){e(b,"b-html",function(a){a.listen(function(){a.$el.html(a.expression(c))})},d)}function q(b,c,d){e(b,"b-context",function(a){var b=a.expression(c);console.log(b);for(var e in c)c.hasOwnProperty(e)&&
        (b[e]=c[e]);b=n(b,d);b.init&&b.init();r.push(b);a=a.$el;z(a,b,d);D(a,b,d);C(a,b,d);B(a,b,d);E(a,b,d);F(a,b,d);H(a,b,d);I(a,b,d);J(a,b,d);K(a,b,d);L(a,b,d);v(a,b,d);G(a,b,d)},d)}var r=[],h={},A="name id style class value disabled readonly checked href for".split(" ");k.scan=q;k.$instances=r;f(function(){k.scan(f("body"),{},{})})})($Binder,jQuery);
</script>