@extends('layouts.master')
@section('stylesheets')
    <link rel="stylesheet" href="{{asset('global/vendor/bootstrap-datepicker/bootstrap-datepicker.css')}}">
    <link rel="stylesheet" href="{{asset('global/vendor/bootstrap-maxlength/bootstrap-maxlength.css')}}">
    <link rel="stylesheet" href="{{ asset('global/vendor/jt-timepicker/jquery-timepicker.css') }}">
@endsection
@section('content')
    <!-- Page -->
    <div class="page ">
        <div class="page-header">
            <h1 class="page-title">{{__('Attendance Based Payroll ')}}</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{url('/')}}">{{__('Home')}}</a></li>
                <li class="breadcrumb-item active">{{__('Attendance Based Payroll')}}</li>
            </ol>
            <div class="page-header-actions">
                <div class="row no-space w-250 hidden-sm-down">

                    <div class="col-sm-6 col-xs-12">
                        <div class="counter">
                            <span class="counter-number font-weight-medium">{{date('Y-m-d')}}</span>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                        <div class="counter">
                            <span class="counter-number font-weight-medium" id="time"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="page-content container-fluid">

            <div class="col-md-12 col-xs-12 col-md-12">
                <div class="panel panel-info panel-line">
                    <div class="panel-heading">
                        <h3 class="panel-title">Attendance Based Payroll</h3>
                        <div class="panel-actions">
                            <button onclick="runPayroll()" class="btn btn-info">Run Payroll</button>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-hover dataTable table-striped w-full" data-plugin="dataTable">
                                <thead>
                                <tr>
                                    <th>{{__('MONTH')}}</th>
                                    <th>{{__('START')}}</th>
                                    <th>{{__('END')}}</th>
                                    <th>{{__('GENERATED BY')}}</th>
                                    <th>{{__('STATUS')}}</th>
                                    <th>{{__('ACTION')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach($payrolls as $payroll)
                                        <tr>
                                          <td>{{ $payroll->month }} {{ $payroll->year }}</td>
                                          <td>{{ $payroll->start }}</td>
                                          <td>{{ $payroll->end }}</td>
                                          <td>{{ $payroll->creator->name }}</td>
                                          <td>{{ $payroll->status }}</td>
                                            <td>
                                                <div class="btn-group" role="group">
                                                    <button type="button" class="btn btn-primary dropdown-toggle" id="exampleIconDropdown1"
                                                            data-toggle="dropdown" aria-expanded="false">
                                                        Action
                                                    </button>
                                                    <div class="dropdown-menu" aria-labelledby="exampleIconDropdown1" role="menu">
                                                        <a style="cursor:pointer;" class="dropdown-item"  href="{{ route('monthly.attendance.payroll',$payroll->id) }}"> &nbsp;View Breakdown</a>
                                                        <a style="cursor:pointer;" class="dropdown-item"  href=""> &nbsp;Send Payslips</a>
                                                        @if($payroll->status=='open')
                                                            <a style="cursor:pointer;" class="dropdown-item"  onclick="return closePayroll({{ $payroll }})"> &nbsp;Close Payroll</a>
                                                        @endif
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


    <div class="modal fade in modal-3d-flip-horizontal modal-info" id="runPayrollModal" aria-hidden="true" role="dialog" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" >
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="training_title">
                        Run Payroll
                    </h4>
                </div>
                <div class="modal-body">
                    <form  id="checkPayrollForm" method="Post" style=" display: inline;">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group col-md-12">
                                    <label class="form-control-label" for="inputBasicFirstName">Select Month</label>
                                    <div class="input-group">
                                    <span class="input-group-addon"><i class="icon fa fa-calendar"
                                                                       aria-hidden="true"></i></span>
                                        <input type="text" class="form-control datepair-date datepair-start" id="date2"
                                               data-plugin="datepicker" name="date" autocomplete="off"
                                               value="{{ $date->format('m-Y') }}" required readonly>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row" id="period_dates">
                            <div class="col-lg-6">
                                <div class="form-group col-md-12">
                                    <label class="form-control-label" for="inputBasicFirstName">Select Start</label>
                                    <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="icon fa fa-calendar" aria-hidden="true"></i>
                                    </span>
                                        <input type="text" class="form-control datepair-date datepair-start" id="startdate"
                                               data-plugin="datepicker" name="start" autocomplete="off"
                                               placeholder="{{ $date->format('d M, Y') }}" value="{{ $date->format('m/d/Y') }}" readonly required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group col-md-12">
                                    <label class="form-control-label" for="inputBasicFirstName">Select End</label>
                                    <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="icon fa fa-calendar" aria-hidden="true"></i>
                                    </span>
                                        <input type="text" class="form-control datepair-date datepair-start" id="startdate"
                                               data-plugin="datepicker" name="end" autocomplete="off"
                                               placeholder="{{ $date->format('d M, Y') }}" value="{{ $date->format('m/d/Y') }}" required readonly>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <button id="run_button" class="btn btn-info" style="margin-left: 10px">Run Payroll</button>
                            </div>
                        </div>
                    </form>

                    <div class="row" id="checkDetails" style="display: none">
                        <div class="col-lg-12" style="margin-left:10px">
                            <h4 id="detailsText"></h4>
                        </div>
                        <form action="" id="confirmRun">
                            @csrf
                            <input type="hidden" name="confirmdate" id="confirmdate">
                            <input type="hidden" name="confirmstart" id="confirmstart">
                            <input type="hidden" name="confirmend" id="confirmend">
                            <div class="row">
                                <div class="col-lg-3">
                                    <button id="confirm" class="btn btn-info" style="margin-left: 20px; display: none">Confirm Payroll</button>
                                </div>
                                <div class="col-lg-3">
                                    <a id="confirm2"  style="text-decoration: none; color: white; display: none" onclick="resetPayroll()" class="btn btn-primary">Reset Form</a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection
@section('scripts')
    <script type="text/javascript">

    </script>
    <script src="{{asset('global/vendor/bootstrap-table/bootstrap-table.min.js')}}"></script>
    <script src="{{asset('global/vendor/bootstrap-table/extensions/mobile/bootstrap-table-mobile.js')}}"></script>
    <script src="{{asset('global/vendor/bootstrap-datepicker/bootstrap-datepicker.js')}}"></script>
    <script src="{{asset('global/vendor/jt-timepicker/jquery.timepicker.min.js')}}"></script>
    <script src="{{asset('global/vendor/datepair/datepair.min.js')}}"></script>
    <script src="{{asset('global/vendor/datepair/jquery.datepair.min.js')}}"></script>
    <script>
        $("#date2").datepicker({
            format: "mm-yyyy",
            viewMode: "months",
            minViewMode: "months",
            orientation: "bottom"
        });
    </script>
    <script type="text/javascript">
        function runPayroll() {
            resetPayroll()
            $('#runPayrollModal').modal();
        }
        function resetPayroll() {
            $("#run_button").show()
            $("#checkDetails").hide()
        }
        $("#date2").on("change", function() {
            $.get('{{ url('/attendance/previous/payroll') }}/'+this.value,function(data){
                if (data==='none') {
                }
                else{
                    console.log(data)
                    $("#startdate").val(data);
                }
            });
        });

        function closePayroll(payroll) {
            alertify.confirm('Are you sure you want to payroll for '+payroll.month+' '+payroll.year+'?', function () {
                alertify.success('Processing this request. Please wait...');
                $.ajax({
                    url: '{{url('attendance/close/payroll')}}/'+payroll.id,
                    type: 'GET',
                    success: function (data, textStatus, jqXHR) {
                        if (data==='success'){
                            alertify.success('Successfully Closed   payroll for '+payroll.month+' '+payroll.year);
                        }
                        else{
                            alertify.error('Something went wrong');
                        }

                        setTimeout(function(){
                            window.location.reload();
                        },2000);
                    },
                    error: function (data, textStatus, jqXHR) {
                        alertify.error('Something went wrong')
                    }
                });
            }, function () {
                alertify.error('Cancelled')
            })
        }

        $(document).on('submit', '#checkPayrollForm', function (event) {
        $("#run_button").hide()
            event.preventDefault();
            var form = $(this);
            var formdata = false;
            if (window.FormData) {
                formdata = new FormData(form[0]);
            }
            $.ajax({
                url: '{{route('check.attendance.payroll')}}',
                data: formdata ? formdata : form.serialize(),
                cache: false,
                contentType: false,
                processData: false,
                type: 'POST',
                success: function (data, textStatus, jqXHR) {
                    toastr.success("Changes saved successfully", 'Success');
                    $("#checkDetails").show()
                    $("#confirmdate").val(data.date);
                    $("#confirmstart").val(data.start);
                    $("#confirmend").val(data.end);

                    $("#detailsText").html(data.details)
                    if (data.show_button==='yes'){
                        $("#confirm").show()
                        $("#confirm2").show()
                    }

                },
                error: function (data, textStatus, jqXHR) {
                    jQuery.each(data['responseJSON'], function (i, val) {
                        jQuery.each(val, function (i, valchild) {
                            toastr.error(valchild[0]);
                        });
                    });
                    $("#run_button").show()
                }
            });

        });

        $(document).on('submit', '#confirmRun', function (event) {
        $("#confirm").hide()
        $("#confirm2").hide()
            event.preventDefault();
            var form = $(this);
            var formdata = false;
            if (window.FormData) {
                formdata = new FormData(form[0]);
            }
            $.ajax({
                url: '{{route('run.attendance.payroll')}}',
                data: formdata ? formdata : form.serialize(),
                cache: false,
                contentType: false,
                processData: false,
                type: 'POST',
                success: function (data, textStatus, jqXHR) {
                    toastr.success("Changes saved successfully", 'Success');
                    resetPayroll();
                    $('#runPayrollModal').modal('toggle');
                    setTimeout(function(){
                        window.location.reload();
                    },2000);

                },
                error: function (data, textStatus, jqXHR) {
                    jQuery.each(data['responseJSON'], function (i, val) {
                        jQuery.each(val, function (i, valchild) {
                            toastr.error(valchild[0]);
                        });
                    });
                    $("#run_button").show()
                }
            });

        });

    </script>
@endsection